config/routes.rb
Rails.application.routes.draw do
  resource :session, only: %i[create destroy]
  resources :users, only: %i[new create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "tops#index"
  resources :posts, only: %i[index create]
  resources :favorites, only: %i[create]
  resources :translate_hieroglyphs, only: %i[create]
  namespace :api do
    resources :translated_texts, only: %i[show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :body, presence: true, length: { maximum: 140 }
  validates :translated_text, length: { maximum: 255 }

  has_many :favorites, dependent: :destroy

  mount_uploader :ogp_image, OgpImageUploader
  mount_uploader :image, ImageUploader
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/api/translated_texts_controller.rb
class Api::TranslatedTextsController < ApplicationController
  def show
    post = Post.find(params[:id])
    render json: { translated_text: post.translated_text }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  add_flash_types :success, :error
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end


    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id])
    end


    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to root_url, error: "𓏤𓃭𓇋𓄿𓋴𓇋 𓋴𓇋𓎼𓈖 𓇋𓈖 𓆑𓇋𓂋𓋴𓏏"
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end


    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/favolites_controller.rb
class FavolitesController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    post.favolites.create!
    redirect_to posts_path
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    post.favorites.create!
    redirect_to posts_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post = Post.new
    @posts = Post.includes(:favorites).order(created_at: :desc)
    post = Post.find_by(id: params[:post])
    set_meta_tags(og: { image: post.image&.url }) if post
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      @posts = Post.all
      render :index
    end
  end

  private

  def post_params
    { body: hierogliph_body, ogp_image: attach_ogp_image, image: params[:post][:image] }
  end

  def attach_ogp_image
    build_ogp_image(hierogliph_body)
  end

  def hierogliph_body
    params[:post][:body].to_hieroglyph
  end

  def build_ogp_image(text)
    begin
      image = MiniMagick::Image.open(Rails.root.join("app", "assets", "images", "ogp.png"))
      image.combine_options do |config|
        config.font Rails.root.join("app", "assets", "fonts", "SegoeUiHistoric.ttf")
        config.fill "white"
        config.gravity "center"
        config.pointsize 65
        config.draw "text 0, 0 '#{text.scan(/.{1,13}/).join("\n")}'"
      end
    rescue => e
      Rails.logger.error("Failed to process image: #{e.message}")
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def create
    user_ids = User.pluck(:id)
    redirect_to root_path, error: "𓃭𓍯𓎼𓇋𓈖 𓆑𓄿𓇋𓃭𓇋𓂧" if user_ids.blank?

    user = User.find(user_ids.sample)
    start_new_session_for user
    redirect_to posts_path, success: "𓃭𓍯𓎼𓇋𓈖 𓆑𓄿𓇋𓃭𓇋𓂧"
  end

  def destroy
    terminate_session
    redirect_to root_path
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  allow_unauthenticated_access only: %i[ index ]

  def index
    post = Post.find_by(id: params[:post])
    set_meta_tags(og: { image: post.image&.url }) if post
  end
end

app/controllers/translate_hieroglyphs_controller.rb
class TranslateHieroglyphsController < ApplicationController
  def create
    TranslateHieroglyphJob.perform_now(params[:post_id])
    redirect_to posts_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email_address, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      site: "hieroglitter",
      title: "hieroglitter",
      reverse: true,
      charset: "utf-8",
      description: "𓇋𓈖𓆑𓍯𓂋𓅓𓄿𓏏𓇋𓍯𓈖 𓋴𓎛𓄿𓂋𓇋𓈖𓎼 𓄿𓏤𓏤 𓆑𓍯𓂋 𓏤𓎛𓄿𓂋𓄿𓍯𓎛",
      canonical: request.original_url,
      separator: "|",
      og: {
        site_name: :site,
        title: :title,
        description: :description,
        type: "website",
        url: request.original_url,
        image: image_url("ogp.png"),
        local: "ja-JP"
      },
      twitter: {
        card: "summary_large_image"
      }
    }
  end

  def twitter_intent_url(post_id)
    "https://twitter.com/intent/tweet?text=%F0%93%8E%9B%F0%93%87%8B%F0%93%87%8B%F0%93%82%8B%F0%93%8D%AF%F0%93%8E%BC%F0%93%83%AD%F0%93%87%8B%F0%93%8F%8F%F0%93%8F%8F%F0%93%87%8B%F0%93%82%8B%20%F0%93%85%B1%F0%93%8D%AF%20%F0%93%8F%8F%F0%93%85%B1%F0%93%8E%A1%F0%93%84%BF%F0%93%8F%8F%F0%93%8F%8F%F0%93%87%8B%20%F0%93%85%93%F0%93%87%8B%F0%93%88%96%F0%93%88%96%F0%93%84%BF%F0%93%85%93%F0%93%8D%AF%20%F0%93%86%91%F0%93%84%BF%F0%93%82%8B%F0%93%84%BF%F0%93%8D%AF%F0%93%88%96%F0%93%87%8B%F0%93%88%96%F0%93%84%BF%F0%93%82%8B%F0%93%8D%AF%F0%93%85%B1%20%0ahttps%3A%2F%2Fhieroglitter-0a0ed1ebffda.herokuapp.com%2Fposts%3Fpost%3D#{post_id}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Hieroglitter" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.ico') %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= display_meta_tags(default_meta_tags) %>

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="bg-desert">
    <%= render 'shared/header' %>
    <main class="min-h-screen container mx-auto pt-3">
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/index.html.erb
<div class="container w-3/4">
  <%= form_with model: Post.new, class: "max-w-screen-md w-full mx-auto border border-neutral-400 px-2 bg-slate-200 my-3 py-3" do |form| %>
    <%= form.label :𓃀𓍯𓂧𓇋 %>
    <div class="form-control">
      <%= form.text_field :body, class: "input input-bordered", placeholder: "𓏤𓃭𓊃 𓅱𓂋𓇋𓏏𓇋 𓃀𓇋 𓄿𓃭𓏤𓎛𓄿𓃀𓇋𓏏 𓍯𓂋 𓆓𓄿𓏤𓄿𓈖𓇋𓋴𓇋" %>
    </div>
    <div class="flex justify-between mt-2">
      <%= form.label :image do %>
        <%= image_tag 'image_icon.svg', class: 'h-8 mt-auto cursor-pointer' %>
        <%= form.file_field :image, class: 'hidden' %>
      <% end %>
      <%= form.submit "𓏤𓍯𓋴𓏏", class: "btn btn-primary tracking-widest" %>
    </div>
  <% end %>
  <% @posts.each do |post| %>
    <div class="card bg-base-100 w-full max-w-screen-md mx-auto bg-slate-200 rounded-none border-b border-neutral-400">
      <div class="card-body">
        <!-- NOTE: Jobの処理が長すぎてHeroku上でうまく動作しないので本番環境に表示しないようにする -->
        <% if Rails.env.development? %>
          <% if post.translated_text.present? %>
            <div class="ml-auto p-1">
              <%= image_tag 'play_button.svg', class: "h-5 play", id: post.id %>
            </div>
          <% else %>
            <div class="badge badge-accent ml-auto p-1" id=<%= "translated_text_#{post.id}" %>>
              <%= link_to "平民用翻訳機能", translate_hieroglyphs_path(post_id: post.id), data: { turbo_method: :post}, onclick: "document.getElementById('translated_text_#{post.id}').classList.add('loading')" %>
            </div>
          <% end %>
        <% end %>
        <p><%= post.body %></p>
        <%= image_tag post.image_url, class: "w-1/2 mx-auto mt-3" if post.image.present? %>
        <div class="flex justify-end">
          <%= link_to favorites_path(post_id: post.id), data: { turbo_method: :post} do %>
            <%= image_tag 'cat-solid-pink.svg', class: "h-4" %>(<%= post.favorites.count %>)
          <% end %>
          <%= link_to twitter_intent_url(post.id) do %>
            <%= image_tag 'dove-solid.svg', class: "h-4 ml-3" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_header.html.erb
<div class="navbar bg-neutral text-neutral-content">
  <%= link_to 'hieroglitter', root_path, class: "btn btn-ghost text-xl" %>
  <% if authenticated? %>
  <div class="flex-none gap-2 ml-auto">
    <div class="dropdown dropdown-end">
      <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar">
        <div class="w-10 rounded-full">
          <%= image_tag Current.user.image_url, class: "w-10 rounded-full" %>
        </div>
      </div>
      <ul
        tabindex="0"
        class="menu menu-sm dropdown-content bg-base-100 rounded-box z-[1] mt-3 w-52 p-2 shadow">
        <li class="text-black"><%= link_to '𓏏𓍯𓏤', root_path %></li>
        <li class="text-black"><%= link_to '𓃭𓍯𓎼𓍯𓅱𓏏', session_path, data: { turbo_method: :delete } %></li>
      </ul>
    </div>
  </div>
  <% end %>
</div>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> rounded-none">
    <%= value %>
  </div>
<% end %>

app/views/tops/index.html.erb
<div class="mb-3">
  <h2 class="welcome-message">
    <span class="text-2xl font-bold drop-shadow-xl bg-stone-400 bg-opacity-25">𓎛𓇋𓃭𓃭𓍯 𓏤𓎛𓄿𓂋𓄿𓍯𓎛</span>
  </h2>
  <p class="text-xl">𓏏𓎛𓇋𓋴 𓇋𓋴 𓄿 𓃀𓍯𓄿𓂋𓂧 𓆑𓍯𓂋 𓏤𓎛𓄿𓂋𓄿𓍯𓎛</p>
  <h2 class="usage mt-3">
    <span class="text-2xl font-bold drop-shadow-xl bg-stone-400 bg-opacity-25">𓅱𓋴𓄿𓎼𓇋</span>
  </h2>
  <p class="text-xl">
    𓏏𓅱𓇋𓇋𓏏 𓏏𓎛𓇋 𓂧𓄿𓇋𓃭𓇋 𓃭𓇋𓆑𓇋 𓍯𓆑 𓏏𓎛𓇋 𓏤𓎛𓄿𓂋𓄿𓍯𓎛
  </p>
  <p class="text-xl">
    𓇋𓏏 𓇋𓋴 𓄿𓅱𓏏𓍯𓅓𓄿𓏏𓇋𓎡𓄿𓃭𓃭𓇋 𓎡𓍯𓈖𓆑𓇋𓂋𓏏𓇋𓂧 𓏏𓍯 𓎛𓇋𓇋𓂋𓍯𓎼𓃭𓇋𓏤𓎛𓋴 𓄿𓈖𓂧 𓏤𓍯𓋴𓏏𓇋𓂧
  </p>
  <p class="text-xl">
    𓏤𓂋𓇋𓋴𓋴 𓏏𓎛𓇋 𓎡𓄿𓏏 𓃀𓅱𓏏𓏏𓍯𓈖 𓍯𓈖 𓄿 𓎼𓍯𓍯𓂧 𓏤𓍯𓋴𓏏 𓄿𓈖𓂧 𓏏𓇋𓃭𓃭 𓏤𓎛𓄿𓂋𓄿𓍯𓎛 𓅱𓎛𓄿𓏏 𓇋𓍯𓅱 𓃭𓇋𓎡𓇋
  </p>
  <h2 class="pharaoh-post-page  mt-3">
    <span class="text-2xl font-bold drop-shadow-xl bg-stone-400 bg-opacity-25">𓏤𓃭𓇋𓄿𓋴𓇋 𓇋𓈖𓏏𓇋𓂋 𓎛𓇋𓂋𓇋</span>
  </h2>
  <%= link_to "𓏤𓎛𓄿𓂋𓄿𓍯𓎛𓃭𓍯𓎼𓇋𓈖", session_path, class: "btn btn-primary mt-1", data: { turbo_method: :post } %>
  <h2 class="mt-3"><span class="text-2xl font-bold drop-shadow-xl">平民の方はこちら</span></h2>
  <%= link_to "ファラオになる方法を調べる", "https://www.google.com/search?q=%E3%83%95%E3%82%A1%E3%83%A9%E3%82%AA%E3%81%AB%E3%81%AA%E3%82%8B%E6%96%B9%E6%B3%95", class: "my-2 text-blue-500 underline" %>
</div>